theme: jekyll-theme-cayman
title: Welcome to the homepage of our Qiskit Monte Carlo quantum state classifier!
description: a project from the Qiskit Advocates Mentorship Program 2021

Pilote project testing by a Monte Carlo simulation a quantum state classifier based on distance matrix computation.
The classifier is applied on a set of separable highly entangled quantum states and uses either an ideal model of measurement count distributions or a front-end empirical model.

Details of the project can be found in [this notebook](https://github.com/Monte-Carlo-quantum-state-classifier/blog-quantum-state-classifier/blob/gh-pages/1_project_description.ipynb)
